### ISSUE TITLE
Feature Request: Next Bin

### ISSUE THREAD

**Issue by craigmcfly** [joemcc-90/leeds-bins-hass#22]
Can you add an entity for the next bin for a particular property, or clarify how I'd create this myself?

**Comment by craigmcfly** [comment]
I've implemented this, so far, which works:

```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - entity_id: "*bins*"
sort:
  method: attribute
  attribute: days
  count: 1
```
