### ISSUE TITLE
Applying attributes to button

### ISSUE THREAD

**Issue by craigmcfly** [joemcc-90/leeds-bins-hass#33]
I'm trying to create a button-card to show me which bin needs emptying next. 

I have the following

```
show_name: false
show_icon: true
type: custom:button-card
entity: sensor.leeds_bins_0000000_nextbin
color: "{{ state_attr('sensor.leeds_bins_0000000_nextbin','colour') }}"
```

but I can't get the colour to apply. Any suggestions?

**Comment by joemcc-90** [comment]
You can't use templates in the color field for the button card it seems, works for me as below.

Go to  **Settings > Devices & Services > Helpers** and press **Create > Template > Template a sensor**, set a name and use state template - {{ state_attr('sensor.leeds_bins_0000000_nextbin', 'colour') | lower }} save it, then edit it and turn off visible so it doesn't show in the HA UI.

Then use below in your button card;

type: custom:button-card
entity: sensor.bin_colour
show_name: false
show_icon: true
icon: mdi:delete
color_type: icon
state:
  - value: "green"
    styles:
      icon:
        - color: green
  - value: "brown"
    styles:
      icon:
        - color: brown
  - value: "black"
    styles:
      icon:
        - color: black

**Comment by craigmcfly** [comment]
okay, so it turns out I was massively over-working this. Because the state is already set on the nextbin entity, I could do this:

```
show_name: false
show_icon: true
type: custom:button-card
entity: sensor.leeds_bins_000000_nextbin
state:
  - value: "General Waste"
    color: black
  - value: "Recycling"
    color: green
  - value: "Garden Waste"
    color: brown
```
